export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_INGREDIENT_FAILED= 'FETCH_INGREDIENT_FAILED';

export const PURCHAGE_INIT= 'PURCHAGE_INIT';
export const PURCHAGE_ORDER_START= 'PURCHAGE_ORDER_START';
export const PURCHAGE_ORDER_SUCCESS= 'PURCHAGE_ORDER_SUCCESS';
export const PURCHAGE_ORDER_FAILED= 'PURCHAGE_ORDER_FAILED';

export const FETCH_ORDER_START= 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS= 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILED= 'FETCH_ORDER_FAILED';


