export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_INGREDIENT_FAILED= 'FETCH_INGREDIENT_FAILED';
export const INIT_INGREDIENTS= 'INIT_INGREDIENTS';

export const PURCHAGE_BURGER= 'PURCHAGE_BURGER';
export const PURCHAGE_INIT= 'PURCHAGE_INIT';
export const PURCHAGE_ORDER_START= 'PURCHAGE_ORDER_START';
export const PURCHAGE_ORDER_SUCCESS= 'PURCHAGE_ORDER_SUCCESS';
export const PURCHAGE_ORDER_FAILED= 'PURCHAGE_ORDER_FAILED';

export const FETCH_ORDERS= 'FETCH_ORDERS';
export const FETCH_ORDER_START= 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS= 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILED= 'FETCH_ORDER_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCESS = 'AUTH_SUCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const CHECK_AUTH_LOGOUT = 'CHECK_AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';


